### ISSUE TITLE
麻烦加个128x128的st7735s屏和240x240的st7789屏

### ISSUE THREAD

**Issue by itschina** [planet0104/USB-Screen#1]
麻烦加个128x128的st7735s屏和240x240的st7789屏，或者麻烦告知下怎么修改屏参数，谢谢

**Comment by planet0104** [comment]
添加好了
`       ScreenSize {
            name: "ST7735".into(),
            width: 128,
            height: 128,
        },
        ScreenSize {
            name: "ST7789".into(),
            width: 320,
            height: 240,
        },
        ScreenSize {
            name: "ST7789".into(),
            width: 240,
            height: 240,
        }];`

**Comment by itschina** [comment]
谢谢
