### ISSUE TITLE
想用在op上面，方便适配下luci-app-*格式的op控制端吗？

### ISSUE THREAD

**Issue by GWan1234** [planet0104/USB-Screen#2]
如题，之前用的i2c小屏幕，oled有这个项目https://github.com/NateLol/luci-app-oled.git
不知道大佬是否方便适配个op的控制端。

**Comment by planet0104** [comment]
我发布的1.1 Release包中的二进制程序(aarch64文件夹中)，是支持在openwrt系统运行的，需要rp2040+ST7735屏幕。

上位机程序是生成的RGB图像，转换成黑白图片也不难。不确定你发的这个代码中，驱动屏幕的协议是什么，如果oled小屏幕的协议能接收黑白的整幅图像，改造起来应该不难。如果不支持图像传输，就不太不好适配了。

**Comment by GWan1234** [comment]
> 我发布的1.1 Release包中的二进制程序(aarch64文件夹中)，是支持在openwrt系统运行的，需要rp2040+ST7735屏幕。
> 
> 上位机程序是生成的RGB图像，转换成黑白图片也不难。不确定你发的这个代码中，驱动屏幕的协议是什么，如果oled小屏幕的协议能接收黑白的整幅图像，改造起来应该不难。如果不支持图像传输，就不太不好适配了。

期待大佬出手，luci在op里面控制比较方便。原项目是个i2c协议的，估摸着差别挺大的。。
